# Generated by Django 4.2.6 on 2023-10-30 19:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL')),
                ('avatar', models.ImageField(blank=True, default='images/avatars/avatar.jpg', upload_to='images/avatars/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg'))], verbose_name='Avatar')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Personal information')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
                ('following', models.ManyToManyField(blank=True, related_name='followers', to='system.profile', verbose_name='Subscriptions')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'db_table': 'app_profiles',
                'ordering': ('user',),
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Letter subject')),
                ('email', models.EmailField(max_length=255, verbose_name='Email address')),
                ('content', models.TextField(verbose_name='Contents of the letter')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date the letter was sent')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Sender IP')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedback',
                'db_table': 'app_feedback',
                'ordering': ['-created_at'],
            },
        ),
    ]
